name: DAST

on:
  pull_request:
    branches:
      - main

jobs:
  dast:
    name: OWASP ZAP BASELINE SCAN 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Building Docker Insecure Acebook Image
        run: docker build --tag insecure-acebook:latest .
      - name: Launching the Insecure Acebook app
        run: docker run -d -p 5000:5000 insecure-acebook

      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "http://localhost:5000"
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable' # optional
          fail_action: false # By default ZAP Docker container will fail with an exit code if it identifies any alerts. 
          
          issue_title: DAST Security Tests # Title for the GitHub issue to be created.
